version: '2'

networks:
  default:
    external:
      name: latelier

services:
  tableau-server:
    image: tableau-server:${TABLEAU_VERSION}
    build:
      context: .
      dockerfile: Dockerfile.${TABLEAU_VERSION}
      args:
        proxy: ${http_proxy}
        TABLEAU_VERSION: ${TABLEAU_VERSION}
        TSM_PASSWORD: ${TSM_PASSWORD}
        ADMIN_PASSWORD: ${TSM_PASSWORD}
    container_name: tableau-server
    hostname: tableau-server
    network_mode: host
    volumes:
      - ./data:/var/opt/tableau
      - ./etc/opt:/etc/opt
      - ./root.tableau:/root/.tableau/
      - ./macrovision:/usr/local/share/macrovision/
      - ./config/odbcinst.ini:/etc/odbcinst.ini
      # - ./etc/systemd/system:/etc/systemd/system
      - ./config:/opt/tableau/docker_build/
      #- ./run:/run
      - ./log:/var/log
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      no_proxy: "127.0.0.1,localhost,tableau,tableau-server"
      TSM_PASSWORD: ${TSM_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "8080:80"
      - "8850:8850"
    privileged: true
    
